### ISSUE TITLE
Passing `{ lat: 0, long: 0}` throws an Invalid Arg error

### ISSUE THREAD

**Issue by 205g0** [yousufkalim/nearby-sort#1]
Here, https://github.com/yousufkalim/nearby-sort/blob/a755012b240631de0e9545fb3c96cbcdcdb5d9db/src/index.ts#L25 it should be rather tested if `lat == null || long == null || ...`, then 0 could pass. What do you think?

**Comment by yousufkalim** [comment]
Hi @205g0,

I've fixed the bug you reported. The code now uses `isNaN(parseFloat(lat))` to check if the lat and long values are in number. This will also handle the case where the lat and long values are null, undefined, string, false.

https://github.com/yousufkalim/nearby-sort/blob/af30663660d26a722ff43bdf5efac0f3601a9719/src/index.ts#L25-L29

The solution you told me will not work if the type is other then null. However, this condition also seems redundant as we already have another check below this. Please let me know if you have any other question.

Thanks,
Yousuf Kalim

I hope this helps!

**Comment by yousufkalim** [comment]
I'm closing the issue as the bug has been fixed, Please don't hesitate to reopen the issue if you have any other concern or suggestion.

**Comment by 205g0** [comment]
> The code now uses `isNaN(parseFloat(lat))`

Much better, thanks for being so responsive. Very nice lib btw!
